ami                     = "ami-840910ee"
availability_zone_0     = "us-east-1a"
availability_zone_1     = "us-east-1b"
env                     = "dev"
key_name                = "personal_dev"
profile                 = "personal"
region                  = "us-east-1"
vpc_cidr                = "10.14.0.0/16"